In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

datasets = pd.read_csv('https://raw.githubusercontent.com/ShuklaRishi/CE147_ML/main/Lab2/Exercise-CarData.csv')
datasets.head()

Unnamed: 0  Price   Age     KM FuelType  HP  MetColor  Automatic    CC  \
0           0  13500  23.0  46986   Diesel  90       1.0          0  2000   
1           1  13750  23.0  72937   Diesel  90       1.0          0  2000   
2           2  13950  24.0  41711   Diesel  90       NaN          0  2000   
3           3  14950  26.0  48000   Diesel  90       0.0          0  2000   
4           4  13750  30.0  38500   Diesel  90       0.0          0  2000   

   Doors  Weight  
0  three    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170

In [3]:
X = datasets.iloc[:, :-1].values 

Y = datasets.iloc[:, -1].values 

print("\n\nInput : \n", X) 
print("\n\nOutput: \n", Y) 



Input : 
 [[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


Output: 
 [1165 1165 1165 ... 1015 1015 1114]


In [4]:
X_new = datasets.iloc[:,1:3].values
print("\n\nX for transformation : \n", X_new)



X for transformation : 
 [[13500.    23.]
 [13750.    23.]
 [13950.    24.]
 ...
 [ 8500.    nan]
 [ 7250.    70.]
 [ 6950.    76.]]


In [5]:
std = StandardScaler()
X_std = std.fit_transform(X_new)
print("\n\nStandardized X : \n", X_std)



Standardized X : 
 [[ 0.76376268 -1.75818903]
 [ 0.83271485 -1.75818903]
 [ 0.88787659 -1.70437596]
 ...
 [-0.6152808          nan]
 [-0.96004167  0.7710253 ]
 [-1.04278428  1.09390373]]
