In [3]:
import numpy as np
import torch 
from torch.autograd import backward

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

# Target (apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

x_input = torch.tensor(inputs)
x_target = torch.tensor(targets)
print(x_input)
print(x_target)



tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [6]:
weight = torch.randin(3,1,requires_grade = True)
bias = torch.randin(1,1,requires_grade = True)

print(weight)
print(bias)

tensor([[0.7008],
        [0.4827],
        [0.2381]], dtype=torch.float64)
tensor([[0.2657]], dtype=torch.float64)


In [17]:
mul = np.dot(x_input, weight)
tensor_mul = torch.tensor(mul)
model = tensor_mul + bias
print(model)

tensor([[ 94.0061],
        [121.7584],
        [139.7307],
        [101.3159],
        [111.6309]], dtype=torch.float64)


In [15]:
comparison = model - targets
print(comparison)
square = comparison * comparison
def MSE(square):
  sum = 0
  for i in range(len(square)):
    sum += square[i]
  print(sum)
  print((sum)/(2*(len(square))))
MSE(square)  

tensor([[38.0061],
        [40.7584],
        [20.7307],
        [79.3159],
        [ 8.6309]], dtype=torch.float64)
tensor([9900.9796], dtype=torch.float64)
tensor([990.0980], dtype=torch.float64)
